{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amblelabs",
    "module": "ait",
    "version": "1.3.0-chore-untempered-schism-recipe-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ait-1.3.0-chore-untempered-schism-recipe-dev+mc.1.20.1.jar",
          "url": "ait-1.3.0-chore-untempered-schism-recipe-dev+mc.1.20.1.jar",
          "size": 69784763,
          "sha512": "f3ce89cccd99496e46b5cff85d5c210bdc413d3735b8976203abcd220156f9bd3e245cb19ee197c4757bf5edd2302b836005d7db7684970b73cbd901f40c09c6",
          "sha256": "2cf82d47edc23e058f8485ea9d655388c001eff4e14b0c2845a6bcc5bb10154b",
          "sha1": "881653406878ce125e955358ca3b3cf12a757505",
          "md5": "098339c0086b8a9137504a83492c0e10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "dev.isxander",
          "module": "yet-another-config-lib",
          "version": {
            "requires": "3.6.1+1.20.1-fabric"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-1.3.0-chore-untempered-schism-recipe-dev+mc.1.20.1.jar",
          "url": "ait-1.3.0-chore-untempered-schism-recipe-dev+mc.1.20.1.jar",
          "size": 69784763,
          "sha512": "f3ce89cccd99496e46b5cff85d5c210bdc413d3735b8976203abcd220156f9bd3e245cb19ee197c4757bf5edd2302b836005d7db7684970b73cbd901f40c09c6",
          "sha256": "2cf82d47edc23e058f8485ea9d655388c001eff4e14b0c2845a6bcc5bb10154b",
          "sha1": "881653406878ce125e955358ca3b3cf12a757505",
          "md5": "098339c0086b8a9137504a83492c0e10"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ait-1.3.0-chore-untempered-schism-recipe-dev+mc.1.20.1-sources.jar",
          "url": "ait-1.3.0-chore-untempered-schism-recipe-dev+mc.1.20.1-sources.jar",
          "size": 68268382,
          "sha512": "728d9ead625a405979464d221b575bd915543b959f9ecc08f58eaca20d638609c8998fdaa90487baef9dadaedfd21bc811bfd7fb956b3703daa701f963a83ef0",
          "sha256": "040db5823e536420dae7077d7f27bba95d785f2fca515ed097521b36970d9a9b",
          "sha1": "39a51f22b64b17e9ed5dd966b405a18418318670",
          "md5": "6e0f021c8e87867ac28fa499574442d0"
        }
      ]
    }
  ]
}
