{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amble",
    "module": "stargate",
    "version": "0.0.0-build.264+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.amblelabs",
          "module": "modkit",
          "version": {
            "requires": "1d67a7a312"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stargate-0.0.0-build.264+mc.1.20.1.jar",
          "url": "stargate-0.0.0-build.264+mc.1.20.1.jar",
          "size": 7822303,
          "sha512": "37e45e19ff4f0e45439778309c3f6c7b5507385e56d8deec924d6db1325e256e908661309896ca766db286ae0c7ed805ad823a6e762a3714a23f97286626e4cc",
          "sha256": "81f134d56c9bd9db1d96f93e54934f067e05f387380e1004e919fe90df0c8a2f",
          "sha1": "616feaf603a9fa13ccf2c9d2086929527d1819e6",
          "md5": "4f497e0f9c73a73b35f1dc933d7a0aaf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.amblelabs",
          "module": "modkit",
          "version": {
            "requires": "1d67a7a312"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "stargate-0.0.0-build.264+mc.1.20.1.jar",
          "url": "stargate-0.0.0-build.264+mc.1.20.1.jar",
          "size": 7822303,
          "sha512": "37e45e19ff4f0e45439778309c3f6c7b5507385e56d8deec924d6db1325e256e908661309896ca766db286ae0c7ed805ad823a6e762a3714a23f97286626e4cc",
          "sha256": "81f134d56c9bd9db1d96f93e54934f067e05f387380e1004e919fe90df0c8a2f",
          "sha1": "616feaf603a9fa13ccf2c9d2086929527d1819e6",
          "md5": "4f497e0f9c73a73b35f1dc933d7a0aaf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "stargate-0.0.0-build.264+mc.1.20.1-sources.jar",
          "url": "stargate-0.0.0-build.264+mc.1.20.1-sources.jar",
          "size": 7673082,
          "sha512": "26077fb0ef015effd8dc26da2a71c242df57143fab3a3318fd6471bd407081ffe2b9aabb23ff3051bca7ea95450a8a3145b42facf603f27c56da4916022fa566",
          "sha256": "7f8aca733783e13eb56303f319c0f3e6b62fed3f03535f36bf4263ad504d5353",
          "sha1": "15c1c4e7c77b677839aae0b05de13d834cbd676e",
          "md5": "dabcd4abbf9063242afaf2c5003a72f3"
        }
      ]
    }
  ]
}
