{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amble",
    "module": "stargate",
    "version": "0.0.0-build.264+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.amblelabs",
          "module": "modkit",
          "version": {
            "requires": "1d67a7a312"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stargate-0.0.0-build.264+mc.1.20.1.jar",
          "url": "stargate-0.0.0-build.264+mc.1.20.1.jar",
          "size": 7822308,
          "sha512": "fdca225aa77a5512f2498ed346672532a29182af6f0124c1beaa286125ab43505ee28350a344e3bde1811a1b31708a4c7ee7459feb97e99a2642620384263ae7",
          "sha256": "9ecc3d41c5004f6fa53ccb05016fbd506a2929338f3af4a5b6158634601a7bb8",
          "sha1": "c643161fce2513686616e0869cc98a31e0000986",
          "md5": "76454439dd8986350e55553cc799cb34"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.amblelabs",
          "module": "modkit",
          "version": {
            "requires": "1d67a7a312"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "stargate-0.0.0-build.264+mc.1.20.1.jar",
          "url": "stargate-0.0.0-build.264+mc.1.20.1.jar",
          "size": 7822308,
          "sha512": "fdca225aa77a5512f2498ed346672532a29182af6f0124c1beaa286125ab43505ee28350a344e3bde1811a1b31708a4c7ee7459feb97e99a2642620384263ae7",
          "sha256": "9ecc3d41c5004f6fa53ccb05016fbd506a2929338f3af4a5b6158634601a7bb8",
          "sha1": "c643161fce2513686616e0869cc98a31e0000986",
          "md5": "76454439dd8986350e55553cc799cb34"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "stargate-0.0.0-build.264+mc.1.20.1-sources.jar",
          "url": "stargate-0.0.0-build.264+mc.1.20.1-sources.jar",
          "size": 7673091,
          "sha512": "3632be35790caa7c27fac26a01f1b06fe62efa9627bc913b3805547b72e0c90424096a3128131ab1e905f8eb551a272d97e77f9164fcbbd15e2baf01a50fb0b8",
          "sha256": "d79dfc713257f5276aa9098522f4e667018cb4e7e58a5a632b1c84f3cff2ab0f",
          "sha1": "c269f71423a34b1e5005e733cf5ea343b014ad24",
          "md5": "9eb7ae5f2417cd32b76bf9861ffc860d"
        }
      ]
    }
  ]
}
