{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amble",
    "module": "ait",
    "version": "1.2.13-feat-hads-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ait-1.2.13-feat-hads-dev+mc.1.20.1.jar",
          "url": "ait-1.2.13-feat-hads-dev+mc.1.20.1.jar",
          "size": 58542912,
          "sha512": "4a277b607401854966aef936ba0758bd753456b9d752bc8a914cab240dce7c188f8a0cc6e2ffe074ac116a97cdb7a2ecdc00c551c49b9e58f5a7863dccca067c",
          "sha256": "5ec46e057c89c2885bb2cf302f6aa6dfcec85afe5a7d3e9151dc57cc3e69835a",
          "sha1": "c27e04a59a1b50136133e0bb7144f7a95e9030c0",
          "md5": "98f78543f4f78e81ec3a09889ef5a447"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "dev.isxander",
          "module": "yet-another-config-lib",
          "version": {
            "requires": "3.6.1+1.20.1-fabric"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-1.2.13-feat-hads-dev+mc.1.20.1.jar",
          "url": "ait-1.2.13-feat-hads-dev+mc.1.20.1.jar",
          "size": 58542912,
          "sha512": "4a277b607401854966aef936ba0758bd753456b9d752bc8a914cab240dce7c188f8a0cc6e2ffe074ac116a97cdb7a2ecdc00c551c49b9e58f5a7863dccca067c",
          "sha256": "5ec46e057c89c2885bb2cf302f6aa6dfcec85afe5a7d3e9151dc57cc3e69835a",
          "sha1": "c27e04a59a1b50136133e0bb7144f7a95e9030c0",
          "md5": "98f78543f4f78e81ec3a09889ef5a447"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ait-1.2.13-feat-hads-dev+mc.1.20.1-sources.jar",
          "url": "ait-1.2.13-feat-hads-dev+mc.1.20.1-sources.jar",
          "size": 57046855,
          "sha512": "4279b9d2f846c5b571241bf5fd97a3f749467255058010665e91bb7d0e75459bae4ffee6adbdefa6369aaf20df170036221082eb3b33ac934a3a3b6140873b5c",
          "sha256": "c0a413015788a17f4bad524aab183c99bd701a89d6aacb9285d264f175b39619",
          "sha1": "ecc7614c47a6cfcbebb0f55f081cc73ce4b58756",
          "md5": "7310b925d6e1ae39e341688e10822d33"
        }
      ]
    }
  ]
}
