{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amble",
    "module": "ait",
    "version": "1.2.13-feat-redux-assets-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-perf-anim-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ait-1.2.13-feat-redux-assets-dev+mc.1.20.1.jar",
          "url": "ait-1.2.13-feat-redux-assets-dev+mc.1.20.1.jar",
          "size": 64067050,
          "sha512": "15538478b2738875256b3bb83e27aa0e4982aeabc88ef0316dd1ca42c54b93585097a3e0a1ada9b9d6b5311724b94cd6359da6a5eb66c67305069af03fffb085",
          "sha256": "8201a35d60cbb191af5c36cda1592dd0bef86e41803ea3cc2c1ff41e7d82223b",
          "sha1": "6864163b52b6f12d35bc0f053c5264fdaaae64fe",
          "md5": "fa8f2a500d55ba84c4bd2a37f46ef4a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-perf-anim-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "dev.isxander",
          "module": "yet-another-config-lib",
          "version": {
            "requires": "3.6.1+1.20.1-fabric"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-1.2.13-feat-redux-assets-dev+mc.1.20.1.jar",
          "url": "ait-1.2.13-feat-redux-assets-dev+mc.1.20.1.jar",
          "size": 64067050,
          "sha512": "15538478b2738875256b3bb83e27aa0e4982aeabc88ef0316dd1ca42c54b93585097a3e0a1ada9b9d6b5311724b94cd6359da6a5eb66c67305069af03fffb085",
          "sha256": "8201a35d60cbb191af5c36cda1592dd0bef86e41803ea3cc2c1ff41e7d82223b",
          "sha1": "6864163b52b6f12d35bc0f053c5264fdaaae64fe",
          "md5": "fa8f2a500d55ba84c4bd2a37f46ef4a7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ait-1.2.13-feat-redux-assets-dev+mc.1.20.1-sources.jar",
          "url": "ait-1.2.13-feat-redux-assets-dev+mc.1.20.1-sources.jar",
          "size": 62682353,
          "sha512": "fd87f1af2c9bbe1cadd47f7cf26fc61f16197358cf59b4b3a23c3954d8f74c19e4ba9d381add00ccd22a41baf492b9af6ef15c36d0430715ca89ac6aa2df475f",
          "sha256": "5a7cbd4a92466f128101abf45bfdcea6f0756873603d065ce8a354b15217ea3e",
          "sha1": "dd2ce91ded1ce692b3462b35c58c8da30c4cbadc",
          "md5": "a2f6eb692133cd81938b1e10aad6699b"
        }
      ]
    }
  ]
}
