{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amblelabs",
    "module": "ait",
    "version": "1.3.0-feat-new-splashes-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ait-1.3.0-feat-new-splashes-dev+mc.1.20.1.jar",
          "url": "ait-1.3.0-feat-new-splashes-dev+mc.1.20.1.jar",
          "size": 69784775,
          "sha512": "bdf20b2b536ac4077b404c52cfc8b98015964dee9ae6925a2c29159cdbeed7659293023c1de0e90be9f543ded7b23758687a5a6ad68317b3d193a66eb24850ef",
          "sha256": "0b92a52764eac7efdad5d2e1e254a9a156e8e35827b56f11036277cbe3a2747d",
          "sha1": "fa8ff2b5a067ea79c41b2cf2f9c11e9bdf295fe7",
          "md5": "a7d5fb9d46dfab2f76621ec8f27f445e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "dev.isxander",
          "module": "yet-another-config-lib",
          "version": {
            "requires": "3.6.1+1.20.1-fabric"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-1.3.0-feat-new-splashes-dev+mc.1.20.1.jar",
          "url": "ait-1.3.0-feat-new-splashes-dev+mc.1.20.1.jar",
          "size": 69784775,
          "sha512": "bdf20b2b536ac4077b404c52cfc8b98015964dee9ae6925a2c29159cdbeed7659293023c1de0e90be9f543ded7b23758687a5a6ad68317b3d193a66eb24850ef",
          "sha256": "0b92a52764eac7efdad5d2e1e254a9a156e8e35827b56f11036277cbe3a2747d",
          "sha1": "fa8ff2b5a067ea79c41b2cf2f9c11e9bdf295fe7",
          "md5": "a7d5fb9d46dfab2f76621ec8f27f445e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ait-1.3.0-feat-new-splashes-dev+mc.1.20.1-sources.jar",
          "url": "ait-1.3.0-feat-new-splashes-dev+mc.1.20.1-sources.jar",
          "size": 68268566,
          "sha512": "cfc10e5ec65692b4c6608328ba09e2c3c171a9e19c607453063b022129e4ed7e55a878eea2967cef2b2d4443232850d85ef10f55c1cfdb32139d706102745787",
          "sha256": "aee504c57bed2cd046401e9dff9edb3678358622abea64c710d89bc70709712a",
          "sha1": "507a2e25267a2f5c12c5e7c8caa3d71f684f4cfa",
          "md5": "e5bcc9c9520c33a205a534237be661be"
        }
      ]
    }
  ]
}
