{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amble",
    "module": "ait",
    "version": "1.2.13-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ait-1.2.13-dev+mc.1.20.1.jar",
          "url": "ait-1.2.13-dev+mc.1.20.1.jar",
          "size": 69784611,
          "sha512": "4850d4825c87a5b040326bed0d087c4436ad4e2723794b4e23e78066ab71c84ebb066e84dbfe9ec54676cc65f39d3f0c40c6ddeea82e171a90f45c1017a59801",
          "sha256": "8da9c0ec6b2fc2d549953eb1a49037803813232129575d66fa4e5754d75c2b34",
          "sha1": "6a637aaf143a8a4a89cc6733b3c4211613c65cf3",
          "md5": "ebf9348de2d7158a6129eb78f722142a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "dev.isxander",
          "module": "yet-another-config-lib",
          "version": {
            "requires": "3.6.1+1.20.1-fabric"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-1.2.13-dev+mc.1.20.1.jar",
          "url": "ait-1.2.13-dev+mc.1.20.1.jar",
          "size": 69784611,
          "sha512": "4850d4825c87a5b040326bed0d087c4436ad4e2723794b4e23e78066ab71c84ebb066e84dbfe9ec54676cc65f39d3f0c40c6ddeea82e171a90f45c1017a59801",
          "sha256": "8da9c0ec6b2fc2d549953eb1a49037803813232129575d66fa4e5754d75c2b34",
          "sha1": "6a637aaf143a8a4a89cc6733b3c4211613c65cf3",
          "md5": "ebf9348de2d7158a6129eb78f722142a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ait-1.2.13-dev+mc.1.20.1-sources.jar",
          "url": "ait-1.2.13-dev+mc.1.20.1-sources.jar",
          "size": 68268272,
          "sha512": "1154778eb2711e190b91f7e79a33cc172831ff01517f64086ad04b5013fd424f337db776ef4d24c37c4567d33e36e8a090755fbea104c7a7e504a8d7a7ffd9f2",
          "sha256": "eb79ee596712dc3fe95c85b74b719732ee2b89d5205a0b88a9a2d1f269dc2504",
          "sha1": "bd636a4287b90729c01c119897313123ab1b4a54",
          "md5": "467a7d8a8f2d93069caca5e943864772"
        }
      ]
    }
  ]
}
