{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amblelabs",
    "module": "ait",
    "version": "1.3.0-fix-ip-issues-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ait-1.3.0-fix-ip-issues-dev+mc.1.20.1.jar",
          "url": "ait-1.3.0-fix-ip-issues-dev+mc.1.20.1.jar",
          "size": 69788126,
          "sha512": "8fdd0f14320506eb60253a71157e209863287bff179228594790688fe9e4cdf6ed48639434f7df72ffb9ea8470c94dfa9a903c4437d54e992cf01f5a8e3874ae",
          "sha256": "b59ec1205b35e61d2df0ef533acec370598f56bcbef585d9f017f952e59edf1b",
          "sha1": "79fc6af1be201304f0c35c2aa222d7c03e41e010",
          "md5": "d66bb85a1a7e9202e6c4e271fbfafb1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "dev.isxander",
          "module": "yet-another-config-lib",
          "version": {
            "requires": "3.6.1+1.20.1-fabric"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-1.3.0-fix-ip-issues-dev+mc.1.20.1.jar",
          "url": "ait-1.3.0-fix-ip-issues-dev+mc.1.20.1.jar",
          "size": 69788126,
          "sha512": "8fdd0f14320506eb60253a71157e209863287bff179228594790688fe9e4cdf6ed48639434f7df72ffb9ea8470c94dfa9a903c4437d54e992cf01f5a8e3874ae",
          "sha256": "b59ec1205b35e61d2df0ef533acec370598f56bcbef585d9f017f952e59edf1b",
          "sha1": "79fc6af1be201304f0c35c2aa222d7c03e41e010",
          "md5": "d66bb85a1a7e9202e6c4e271fbfafb1c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ait-1.3.0-fix-ip-issues-dev+mc.1.20.1-sources.jar",
          "url": "ait-1.3.0-fix-ip-issues-dev+mc.1.20.1-sources.jar",
          "size": 68269490,
          "sha512": "ff1537728250c4730404cbabacf1bf47e79acd7dbe26664f527ee972a7734da84d0c8708ab513dd328434712afcfba23f0207843a6ccd5da6576872c6975da4f",
          "sha256": "49e28caeb7c90855b2ae04dc2e94893b25c06cb2b12bca80123f1a073c295474",
          "sha1": "e5e057748b2566e51c2dd631e91662da2ff9d389",
          "md5": "3676d8e64d63e3c0823766e6761a11f2"
        }
      ]
    }
  ]
}
