{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amblelabs",
    "module": "ait",
    "version": "1.3.0-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ait-1.3.0-dev+mc.1.20.1.jar",
          "url": "ait-1.3.0-dev+mc.1.20.1.jar",
          "size": 69788023,
          "sha512": "a7d4010f8c64ddf4deb911a6a5f872dc684f044bd71127231e08ce1931e87d5e3d96bbc935eca1a38acae82acb148b8fa4e24dccf6906ee4424b681201291661",
          "sha256": "24846ed397f2d3725436b213e8c674ed6d0d438483e25dbc0678fd14264de57b",
          "sha1": "c35badbbaaa854c7758cea4376cb4582c9415965",
          "md5": "235ffe77ec33f2fefecf11bfec38acab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "dev.isxander",
          "module": "yet-another-config-lib",
          "version": {
            "requires": "3.6.1+1.20.1-fabric"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-1.3.0-dev+mc.1.20.1.jar",
          "url": "ait-1.3.0-dev+mc.1.20.1.jar",
          "size": 69788023,
          "sha512": "a7d4010f8c64ddf4deb911a6a5f872dc684f044bd71127231e08ce1931e87d5e3d96bbc935eca1a38acae82acb148b8fa4e24dccf6906ee4424b681201291661",
          "sha256": "24846ed397f2d3725436b213e8c674ed6d0d438483e25dbc0678fd14264de57b",
          "sha1": "c35badbbaaa854c7758cea4376cb4582c9415965",
          "md5": "235ffe77ec33f2fefecf11bfec38acab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ait-1.3.0-dev+mc.1.20.1-sources.jar",
          "url": "ait-1.3.0-dev+mc.1.20.1-sources.jar",
          "size": 68269469,
          "sha512": "261949e358f401787c5d2598639cf6629dfb3c0893f164633d74df4d4c11f028639053945fb91047f3ad5bddfead207d3469c99727f91990b3a2087932fefc86",
          "sha256": "19a69f3c3a7f6da68806ee1e3144c5d5e0ceaa3b2bb2ef3c62bc199dc13ff7c1",
          "sha1": "9706973a18be6ac46d09b3a125ca6b5d5b77009b",
          "md5": "0307dd9f71c106a8aa7d15316efc0e8a"
        }
      ]
    }
  ]
}
