{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amblelabs",
    "module": "ait",
    "version": "1.3.0-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ait-1.3.0-dev+mc.1.20.1.jar",
          "url": "ait-1.3.0-dev+mc.1.20.1.jar",
          "size": 69787949,
          "sha512": "a339184d55f5dc6f31ec4bdcdc42575d4ed469644899c996eda878545396ec9e96ecf6553eba4c673aec89d4c20a5d34a1c387e3b35e8368b3579fef4dbe19b8",
          "sha256": "01410211c8a2d8469339e70ec355188dbbc3a74c7b8371285457b7e965b46118",
          "sha1": "2c39f856b5ab71d3786a017a4b11ca794272307b",
          "md5": "b07acc6ec572b22846c7a819942f1d96"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "dev.isxander",
          "module": "yet-another-config-lib",
          "version": {
            "requires": "3.6.1+1.20.1-fabric"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-1.3.0-dev+mc.1.20.1.jar",
          "url": "ait-1.3.0-dev+mc.1.20.1.jar",
          "size": 69787949,
          "sha512": "a339184d55f5dc6f31ec4bdcdc42575d4ed469644899c996eda878545396ec9e96ecf6553eba4c673aec89d4c20a5d34a1c387e3b35e8368b3579fef4dbe19b8",
          "sha256": "01410211c8a2d8469339e70ec355188dbbc3a74c7b8371285457b7e965b46118",
          "sha1": "2c39f856b5ab71d3786a017a4b11ca794272307b",
          "md5": "b07acc6ec572b22846c7a819942f1d96"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ait-1.3.0-dev+mc.1.20.1-sources.jar",
          "url": "ait-1.3.0-dev+mc.1.20.1-sources.jar",
          "size": 68269419,
          "sha512": "ac1286c29e5f3b073b4bb984cdb2b421a16d1a05a0f42c638c6e3d2a68a0b6b89fbd79c744e72635e13b460343762e00c1e1913eb62fcbd5d489fad4afb1e841",
          "sha256": "aaafdb315c9d5f32a1957ee60ca5e30344be9bc40f72ebba52561344aeb3a718",
          "sha1": "6f473e17df1534deebe896170060bf93a1a8054d",
          "md5": "dbe30d03740ec733a2a8c2dcfba97989"
        }
      ]
    }
  ]
}
