{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amblelabs",
    "module": "ait",
    "version": "1.3.0-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ait-1.3.0-dev+mc.1.20.1.jar",
          "url": "ait-1.3.0-dev+mc.1.20.1.jar",
          "size": 69789340,
          "sha512": "179243ef8e8092e4bc7b3808c0d051b698e2b211de2fdba47b0d26d0eccea1cfbaf7758e1e9c9ffc71a8c8ba95bff8a671ed208ad8883c7410ab44fa33e26922",
          "sha256": "81eb990802003391a638c3140c2188a4521c6f7b8b75afe6a2e29f5cf7433a28",
          "sha1": "d0a1856092fbbdc74875e6fdedec171cb4efedbf",
          "md5": "56c262b5c8ea04750d54cc5fc5f67900"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "dev.isxander",
          "module": "yet-another-config-lib",
          "version": {
            "requires": "3.6.1+1.20.1-fabric"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-1.3.0-dev+mc.1.20.1.jar",
          "url": "ait-1.3.0-dev+mc.1.20.1.jar",
          "size": 69789340,
          "sha512": "179243ef8e8092e4bc7b3808c0d051b698e2b211de2fdba47b0d26d0eccea1cfbaf7758e1e9c9ffc71a8c8ba95bff8a671ed208ad8883c7410ab44fa33e26922",
          "sha256": "81eb990802003391a638c3140c2188a4521c6f7b8b75afe6a2e29f5cf7433a28",
          "sha1": "d0a1856092fbbdc74875e6fdedec171cb4efedbf",
          "md5": "56c262b5c8ea04750d54cc5fc5f67900"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ait-1.3.0-dev+mc.1.20.1-sources.jar",
          "url": "ait-1.3.0-dev+mc.1.20.1-sources.jar",
          "size": 68269955,
          "sha512": "ddd9c9a6ca3b1fc150730ce378328a06ed8905f7112002079967b120d0ad16d1b6b600a20584cfef96fd5e7e9d47e92413b9eefc38974a8b3ce68ed763f8cc8d",
          "sha256": "c23017f0055e3dd1f2870354d02adfe36b7913b9a19cf9f9812856b9b8906c36",
          "sha1": "9ebacbf76eb963b766d17631d6e3f81eef6a0f3e",
          "md5": "5cba0bc3187b48ac4968873733842008"
        }
      ]
    }
  ]
}
