{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amble",
    "module": "ait",
    "version": "1.2.13-fix-consoles-animation-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ait-1.2.13-fix-consoles-animation-dev+mc.1.20.1.jar",
          "url": "ait-1.2.13-fix-consoles-animation-dev+mc.1.20.1.jar",
          "size": 60737227,
          "sha512": "d24615cf20f8bd6b4afae295486110c41a4975fb5de478f3830029ae4e17b832873613da25eab145275e31dafd967cdee09e984fc85a08551f40301d9f350d2a",
          "sha256": "55d463431cfeb315825232f1c9ad690433115226ab9ef6b24f13c5f56db10608",
          "sha1": "3d63e96c6179f704b310c38d4c9745377867c3ce",
          "md5": "2723f90fd6d3f7f14a0aeca487e68405"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "dev.isxander",
          "module": "yet-another-config-lib",
          "version": {
            "requires": "3.6.1+1.20.1-fabric"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-1.2.13-fix-consoles-animation-dev+mc.1.20.1.jar",
          "url": "ait-1.2.13-fix-consoles-animation-dev+mc.1.20.1.jar",
          "size": 60737227,
          "sha512": "d24615cf20f8bd6b4afae295486110c41a4975fb5de478f3830029ae4e17b832873613da25eab145275e31dafd967cdee09e984fc85a08551f40301d9f350d2a",
          "sha256": "55d463431cfeb315825232f1c9ad690433115226ab9ef6b24f13c5f56db10608",
          "sha1": "3d63e96c6179f704b310c38d4c9745377867c3ce",
          "md5": "2723f90fd6d3f7f14a0aeca487e68405"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ait-1.2.13-fix-consoles-animation-dev+mc.1.20.1-sources.jar",
          "url": "ait-1.2.13-fix-consoles-animation-dev+mc.1.20.1-sources.jar",
          "size": 59223316,
          "sha512": "24dd0352cd6955f05ff30e81db0101f76cbc6dbb8a9ecece7b3bf72af66009992c184d429d5c46bbc43c346f74b60cf2fb0e266fb5dd23583382f1db0f7cc458",
          "sha256": "4813d7dcb499095abbd1542f2c27052578fa6a4a2f93a2adf51f3792b374be71",
          "sha1": "c7351ebe75a45feaaac4683e302f0f8c0f9f1290",
          "md5": "a1044927f468a674f3059b962c5330bb"
        }
      ]
    }
  ]
}
