{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amblelabs",
    "module": "ait",
    "version": "1.3.0-fix-rendering-queue-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ait-1.3.0-fix-rendering-queue-dev+mc.1.20.1.jar",
          "url": "ait-1.3.0-fix-rendering-queue-dev+mc.1.20.1.jar",
          "size": 69784500,
          "sha512": "7a52dddb9c714294648bb4bbaba844d9a7ed5fc211f0da4db48ddb94d9faf66a3d473634c01ae59702ba248c1d19233584ae172dced3a9415a7eea09d4f93fb3",
          "sha256": "8045a0a8184bb86d8ed81dbafd5f7ab84da7f6c56aa1f887b31da2575c172eec",
          "sha1": "a1d3ced62a13c0de31f79e1575e1fcf7e199e604",
          "md5": "6b3efdfbea35702c0a64a1c142dff9a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "dev.isxander",
          "module": "yet-another-config-lib",
          "version": {
            "requires": "3.6.1+1.20.1-fabric"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-1.3.0-fix-rendering-queue-dev+mc.1.20.1.jar",
          "url": "ait-1.3.0-fix-rendering-queue-dev+mc.1.20.1.jar",
          "size": 69784500,
          "sha512": "7a52dddb9c714294648bb4bbaba844d9a7ed5fc211f0da4db48ddb94d9faf66a3d473634c01ae59702ba248c1d19233584ae172dced3a9415a7eea09d4f93fb3",
          "sha256": "8045a0a8184bb86d8ed81dbafd5f7ab84da7f6c56aa1f887b31da2575c172eec",
          "sha1": "a1d3ced62a13c0de31f79e1575e1fcf7e199e604",
          "md5": "6b3efdfbea35702c0a64a1c142dff9a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ait-1.3.0-fix-rendering-queue-dev+mc.1.20.1-sources.jar",
          "url": "ait-1.3.0-fix-rendering-queue-dev+mc.1.20.1-sources.jar",
          "size": 68268301,
          "sha512": "3a0a420eb505f4dde95f12185c997d04ea241c0dbf58b1cfe9125c817e9e5204ced697a6ed14a1f477434ac1ad56f446adcee58cd06f27af6ff932d3472d0260",
          "sha256": "b9df24e3421a4812fbad7e69fcc80e1b938ef724080c14423d7b698cf4260240",
          "sha1": "2f144b370a00f7eefefcbe8e7239e8a9e8dd3707",
          "md5": "48a5a31e4236386348132747e08bf472"
        }
      ]
    }
  ]
}
