{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amblelabs",
    "module": "ait",
    "version": "1.3.0-feat-autopilot-config-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ait-1.3.0-feat-autopilot-config-dev+mc.1.20.1.jar",
          "url": "ait-1.3.0-feat-autopilot-config-dev+mc.1.20.1.jar",
          "size": 69784831,
          "sha512": "882618a7d653ceeb7d10986c4b3a6e0aae86484021f597b5e25b029386d4329ca1de7353c369f10d655a58e4e974b932d25aef820c5b9e63321c5276f13c95f8",
          "sha256": "aebc47a7433181a656ca87315f3c4964d6d44fe940c21e9794295533466527a3",
          "sha1": "6f0667caa9c2a2830a863fd0b3e6e2f2a51f9be8",
          "md5": "e2f979cf3732c1777f42bfacce77681b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "dev.isxander",
          "module": "yet-another-config-lib",
          "version": {
            "requires": "3.6.1+1.20.1-fabric"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-1.3.0-feat-autopilot-config-dev+mc.1.20.1.jar",
          "url": "ait-1.3.0-feat-autopilot-config-dev+mc.1.20.1.jar",
          "size": 69784831,
          "sha512": "882618a7d653ceeb7d10986c4b3a6e0aae86484021f597b5e25b029386d4329ca1de7353c369f10d655a58e4e974b932d25aef820c5b9e63321c5276f13c95f8",
          "sha256": "aebc47a7433181a656ca87315f3c4964d6d44fe940c21e9794295533466527a3",
          "sha1": "6f0667caa9c2a2830a863fd0b3e6e2f2a51f9be8",
          "md5": "e2f979cf3732c1777f42bfacce77681b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ait-1.3.0-feat-autopilot-config-dev+mc.1.20.1-sources.jar",
          "url": "ait-1.3.0-feat-autopilot-config-dev+mc.1.20.1-sources.jar",
          "size": 68268412,
          "sha512": "98456cdfe6148ba7c525d2a3ccffc516747031febc6d4817d57d848df14cb1683c85e202cf3d71ef87ebde27eaa9c016ea83c508a06f78aa27f17fd4739c45a4",
          "sha256": "f354e1385a866cc63cd6570e393adfc90ecf59cbaa3e4645208b9827de016c85",
          "sha1": "7d1922fdc35e9d7866b25e08c30eee18570da9bb",
          "md5": "084e4dccb5fb5d26e83929a484acd127"
        }
      ]
    }
  ]
}
