{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amble",
    "module": "ait",
    "version": "1.2.13-copilot-fix-creeper-ignite-overload-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ait-1.2.13-copilot-fix-creeper-ignite-overload-dev+mc.1.20.1.jar",
          "url": "ait-1.2.13-copilot-fix-creeper-ignite-overload-dev+mc.1.20.1.jar",
          "size": 58531312,
          "sha512": "c06f391c8f5407f1f9c6c46846e17c0719adf6bba57a3759f4a78b813618a99956bbb2d2e6e6d53b15349212e99f8009daa0aaba57f4d1e40e74f66db6ea1c54",
          "sha256": "b9e024315d9fc9dd507a9a2e50dcf5635aefcafd8467832f97558585fb82f01d",
          "sha1": "ea4da9ec85267a82abb8cfbee8be41b86a67a1e6",
          "md5": "38fe3a680965cf9358be83bb0422161d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "dev.isxander",
          "module": "yet-another-config-lib",
          "version": {
            "requires": "3.6.1+1.20.1-fabric"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-1.2.13-copilot-fix-creeper-ignite-overload-dev+mc.1.20.1.jar",
          "url": "ait-1.2.13-copilot-fix-creeper-ignite-overload-dev+mc.1.20.1.jar",
          "size": 58531312,
          "sha512": "c06f391c8f5407f1f9c6c46846e17c0719adf6bba57a3759f4a78b813618a99956bbb2d2e6e6d53b15349212e99f8009daa0aaba57f4d1e40e74f66db6ea1c54",
          "sha256": "b9e024315d9fc9dd507a9a2e50dcf5635aefcafd8467832f97558585fb82f01d",
          "sha1": "ea4da9ec85267a82abb8cfbee8be41b86a67a1e6",
          "md5": "38fe3a680965cf9358be83bb0422161d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ait-1.2.13-copilot-fix-creeper-ignite-overload-dev+mc.1.20.1-sources.jar",
          "url": "ait-1.2.13-copilot-fix-creeper-ignite-overload-dev+mc.1.20.1-sources.jar",
          "size": 57037658,
          "sha512": "9a8fc687ecd32ab85bc11cf5c7ddba7af790aa020441e220cf73e180f0817822a5e7b576120b78504ad1e54290243cdadf337158b48058788667e5667427af09",
          "sha256": "ea6b3a24251989ce53acdff8d2adbce6ac704a616c92d3cea75b44987cfa07ce",
          "sha1": "f5bd8545c529322dfc803c9cd5ab52a5c0aeb4fb",
          "md5": "adf184d8024d497d299b3a29c4cceceb"
        }
      ]
    }
  ]
}
