{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amble",
    "module": "stargate",
    "version": "0.0.0-build.273+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-build.138-feat-ports+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stargate-0.0.0-build.273+mc.1.20.1.jar",
          "url": "stargate-0.0.0-build.273+mc.1.20.1.jar",
          "size": 7823613,
          "sha512": "96cd7ea2dd6b4873838ffc0b7c5867005df388c5af22b5f7c834bdc9576a0e3a184a7df81bba515e03e1dfa0e50c1a9c9ce89a18742074f5bf32597410f90097",
          "sha256": "ac227fff9aa7bf22cd51612844f092e423c5a41693d1e8feb759e6a3a61a40f0",
          "sha1": "61e6455f7f0ee8850716064a2ce2422abc29c350",
          "md5": "5ef5813db395427401b3d18dffd203b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-build.138-feat-ports+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "stargate-0.0.0-build.273+mc.1.20.1.jar",
          "url": "stargate-0.0.0-build.273+mc.1.20.1.jar",
          "size": 7823613,
          "sha512": "96cd7ea2dd6b4873838ffc0b7c5867005df388c5af22b5f7c834bdc9576a0e3a184a7df81bba515e03e1dfa0e50c1a9c9ce89a18742074f5bf32597410f90097",
          "sha256": "ac227fff9aa7bf22cd51612844f092e423c5a41693d1e8feb759e6a3a61a40f0",
          "sha1": "61e6455f7f0ee8850716064a2ce2422abc29c350",
          "md5": "5ef5813db395427401b3d18dffd203b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "stargate-0.0.0-build.273+mc.1.20.1-sources.jar",
          "url": "stargate-0.0.0-build.273+mc.1.20.1-sources.jar",
          "size": 7674544,
          "sha512": "869afa872447123dacde2e0c1590a298694cf9a0b9d001c7dd13bc279ce542adec5811b0102be89866425e440a23b0618019ccc607b8eaec692ee460c99a5ca2",
          "sha256": "bab1f418ffdea5350c603385bf32c0cc4c547ac2ac6791dd13df617c540390bc",
          "sha1": "829bd6f838b5bb2dce109c44fb4525264c528936",
          "md5": "3f760df2afcfb96c50100cfa292e1df7"
        }
      ]
    }
  ]
}
