{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amble",
    "module": "ait",
    "version": "1.2.13-fix-no_texture_coral_leaves-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ait-1.2.13-fix-no_texture_coral_leaves-dev+mc.1.20.1.jar",
          "url": "ait-1.2.13-fix-no_texture_coral_leaves-dev+mc.1.20.1.jar",
          "size": 58445360,
          "sha512": "c625f361ccafddd9520d795b6865bfb7bfff82eb813fabc7ba55f9a1d1473a040235385d0612a8c2143746b2d83c1acf316308cb41b7cdb5ba22b0656f8cb3a5",
          "sha256": "2c2f339d3da162d69b2b92845a87e3d07c858fb5ae36c3a73a0bb72ed972c181",
          "sha1": "a84b9ef692ecf24cf3145e92a03dc4e0b1e0b70a",
          "md5": "317a414adf0cce95fe742d374ae1f9e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "dev.isxander",
          "module": "yet-another-config-lib",
          "version": {
            "requires": "3.6.1+1.20.1-fabric"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-1.2.13-fix-no_texture_coral_leaves-dev+mc.1.20.1.jar",
          "url": "ait-1.2.13-fix-no_texture_coral_leaves-dev+mc.1.20.1.jar",
          "size": 58445360,
          "sha512": "c625f361ccafddd9520d795b6865bfb7bfff82eb813fabc7ba55f9a1d1473a040235385d0612a8c2143746b2d83c1acf316308cb41b7cdb5ba22b0656f8cb3a5",
          "sha256": "2c2f339d3da162d69b2b92845a87e3d07c858fb5ae36c3a73a0bb72ed972c181",
          "sha1": "a84b9ef692ecf24cf3145e92a03dc4e0b1e0b70a",
          "md5": "317a414adf0cce95fe742d374ae1f9e4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ait-1.2.13-fix-no_texture_coral_leaves-dev+mc.1.20.1-sources.jar",
          "url": "ait-1.2.13-fix-no_texture_coral_leaves-dev+mc.1.20.1-sources.jar",
          "size": 56958517,
          "sha512": "b0df20ed246e658d8ac39c71c6aa7117e166fea3f530d13c2a0dd44d86483218dd5bff89cf577d3e959baad8241c3b964eed4ab708093fe6c1a1a2de6d8f7ffe",
          "sha256": "3b51a284ca5dc2616a297ed444d8468782c2a2057cb8b1a812fe47e71c110ced",
          "sha1": "e27bb741a9ae84d140aca355ae7f36e5ac222743",
          "md5": "b896b0047e96e4c736dc4470e2098e23"
        }
      ]
    }
  ]
}
