{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amble",
    "module": "stargate",
    "version": "0.0.0-build.270+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-build.138-feat-ports+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stargate-0.0.0-build.270+mc.1.20.1.jar",
          "url": "stargate-0.0.0-build.270+mc.1.20.1.jar",
          "size": 7822978,
          "sha512": "a10959d8c9e983072e3b8e0cfd9c66fd93d970cb51f0ce3abde10a5a31238b6bba0be38c0a43b5396133344e236114a2b7c676f1cc2a6ae5d8f24dcb5ad1157e",
          "sha256": "ae65cf66a1fc0f39095cf873cac396d880182e53bd66701cfd8250f5f490bc12",
          "sha1": "36994a6f228f6f1e675355abf5fa38af6da8af52",
          "md5": "a16568c2a4b0e29cd5bf9b7c623ac99d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-build.138-feat-ports+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "stargate-0.0.0-build.270+mc.1.20.1.jar",
          "url": "stargate-0.0.0-build.270+mc.1.20.1.jar",
          "size": 7822978,
          "sha512": "a10959d8c9e983072e3b8e0cfd9c66fd93d970cb51f0ce3abde10a5a31238b6bba0be38c0a43b5396133344e236114a2b7c676f1cc2a6ae5d8f24dcb5ad1157e",
          "sha256": "ae65cf66a1fc0f39095cf873cac396d880182e53bd66701cfd8250f5f490bc12",
          "sha1": "36994a6f228f6f1e675355abf5fa38af6da8af52",
          "md5": "a16568c2a4b0e29cd5bf9b7c623ac99d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "stargate-0.0.0-build.270+mc.1.20.1-sources.jar",
          "url": "stargate-0.0.0-build.270+mc.1.20.1-sources.jar",
          "size": 7673865,
          "sha512": "217ddc9af1b80c49f053a338b81a3a786d2b88d5b3a105da61feb12a7e07a479a7141c7bd8d5137a54231b769a6d1cf0e21f14ca822192b369c73fb73b82f952",
          "sha256": "e97c7e8d6ecebbc899db944c32a812b5e98c50bf33e91b047272fc1263da05bf",
          "sha1": "f782a36488e7b52a2ca90093b9b349a141bc28ed",
          "md5": "016f569fbdfebf9da63035aa609cf252"
        }
      ]
    }
  ]
}
