{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amblelabs",
    "module": "ait",
    "version": "1.3.0-fix-stupidIPstuff-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ait-1.3.0-fix-stupidIPstuff-dev+mc.1.20.1.jar",
          "url": "ait-1.3.0-fix-stupidIPstuff-dev+mc.1.20.1.jar",
          "size": 69784863,
          "sha512": "880728839270677a6a01b6309e9e71d0b4f00b837654d896986ee0cd2723b72c392879545c6b4a093aa50be165490ff63b22a235e86e3d05c2e435e969955e1f",
          "sha256": "e67dd8c42b8513ea024686b5ef32be6a9b046d82370629374040b104b3c00c74",
          "sha1": "17a9496a1f7cf662b7fe34cd3bb5feae1abf7690",
          "md5": "cc69d2a3034d679b82b45789b7478a09"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "dev.isxander",
          "module": "yet-another-config-lib",
          "version": {
            "requires": "3.6.1+1.20.1-fabric"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-1.3.0-fix-stupidIPstuff-dev+mc.1.20.1.jar",
          "url": "ait-1.3.0-fix-stupidIPstuff-dev+mc.1.20.1.jar",
          "size": 69784863,
          "sha512": "880728839270677a6a01b6309e9e71d0b4f00b837654d896986ee0cd2723b72c392879545c6b4a093aa50be165490ff63b22a235e86e3d05c2e435e969955e1f",
          "sha256": "e67dd8c42b8513ea024686b5ef32be6a9b046d82370629374040b104b3c00c74",
          "sha1": "17a9496a1f7cf662b7fe34cd3bb5feae1abf7690",
          "md5": "cc69d2a3034d679b82b45789b7478a09"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ait-1.3.0-fix-stupidIPstuff-dev+mc.1.20.1-sources.jar",
          "url": "ait-1.3.0-fix-stupidIPstuff-dev+mc.1.20.1-sources.jar",
          "size": 68268501,
          "sha512": "8817b024ea8df141cbbd915fe67c6b26c9421f68283301dcfae3f97d0af023a22eb26b4b6531f04d4e0b213db0ee1c534a304c52fd2cdb99f46fa2e5f900bec4",
          "sha256": "2f2407b3f9e304689e22257f91303458b67c90917e479559d55c9ed8a1727e4f",
          "sha1": "63ce1814ad35784e6eff5ea0ff22f3045f24ac31",
          "md5": "c5d4fbb75afd8edfaa50f89307c4265f"
        }
      ]
    }
  ]
}
