{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amble",
    "module": "stargate",
    "version": "0.0.0-build.265+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.amblelabs",
          "module": "modkit",
          "version": {
            "requires": "1d67a7a312"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stargate-0.0.0-build.265+mc.1.20.1.jar",
          "url": "stargate-0.0.0-build.265+mc.1.20.1.jar",
          "size": 7822306,
          "sha512": "f4db4cc2fc1c5b59d825c3e99f9c50094591ff475c285103cfc2c9d64f6f127f300b0b69daa369182b3704c28840147df1d38994d8c8c80df4e9348bf88d020d",
          "sha256": "36b4a3e4777333dca275893b942ee5fcdb9f6590c91be119eea29204dfa8a518",
          "sha1": "416cfeb6d3e85af0edf2696fd3d956356192d5ea",
          "md5": "4c89584f81e6d100488be9434ef76f77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.amblelabs",
          "module": "modkit",
          "version": {
            "requires": "1d67a7a312"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "stargate-0.0.0-build.265+mc.1.20.1.jar",
          "url": "stargate-0.0.0-build.265+mc.1.20.1.jar",
          "size": 7822306,
          "sha512": "f4db4cc2fc1c5b59d825c3e99f9c50094591ff475c285103cfc2c9d64f6f127f300b0b69daa369182b3704c28840147df1d38994d8c8c80df4e9348bf88d020d",
          "sha256": "36b4a3e4777333dca275893b942ee5fcdb9f6590c91be119eea29204dfa8a518",
          "sha1": "416cfeb6d3e85af0edf2696fd3d956356192d5ea",
          "md5": "4c89584f81e6d100488be9434ef76f77"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "stargate-0.0.0-build.265+mc.1.20.1-sources.jar",
          "url": "stargate-0.0.0-build.265+mc.1.20.1-sources.jar",
          "size": 7673088,
          "sha512": "b63cd964da239cf9ec8f79c9e28786999ad3a25e6328effcb8a3c1ffabf3ce3a78468989b07a6c51c28aa195c5f3428b4e9aba443dd171b542dfd70262c2f7d1",
          "sha256": "5b5c4e84e01db12a1ae2ff06decd5bccc69490183ae2b2e0f533f59359d78d1a",
          "sha1": "13956a7f08c01554e67e9b0e6476dcbeaf06618e",
          "md5": "48c8b81b744b153948e65f9c4dad02dc"
        }
      ]
    }
  ]
}
