{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amble",
    "module": "ait",
    "version": "1.2.13-feat-very-important-ait-update-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ait-1.2.13-feat-very-important-ait-update-dev+mc.1.20.1.jar",
          "url": "ait-1.2.13-feat-very-important-ait-update-dev+mc.1.20.1.jar",
          "size": 58448713,
          "sha512": "fd07c047db0a3763554c2d221002e5e86d8424b7ac6161922545aca795c6e5ec5b9d3f63405a42ef829f11f31b98baf0633f4b3ec93bac72cf3316d5a32a8b9c",
          "sha256": "5fc60eb3b5b83fe3325304cb748a4a8547761dbccdd7c3a79fa8bc30e7c93287",
          "sha1": "633f5b44ac7f9909dbaf20464427ccfabdedae4b",
          "md5": "c4cdaf7d0dc066ca8d3f7e1d161b9c42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "dev.isxander",
          "module": "yet-another-config-lib",
          "version": {
            "requires": "3.6.1+1.20.1-fabric"
          }
        },
        {
          "group": "com.github.iPortalTeam.ImmersivePortalsMod",
          "module": "imm_ptl_core",
          "version": {
            "requires": "v3.3.9-mc1.20.1"
          }
        },
        {
          "group": "com.github.iPortalTeam.ImmersivePortalsMod",
          "module": "q_misc_util",
          "version": {
            "requires": "v3.3.9-mc1.20.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-1.2.13-feat-very-important-ait-update-dev+mc.1.20.1.jar",
          "url": "ait-1.2.13-feat-very-important-ait-update-dev+mc.1.20.1.jar",
          "size": 58448713,
          "sha512": "fd07c047db0a3763554c2d221002e5e86d8424b7ac6161922545aca795c6e5ec5b9d3f63405a42ef829f11f31b98baf0633f4b3ec93bac72cf3316d5a32a8b9c",
          "sha256": "5fc60eb3b5b83fe3325304cb748a4a8547761dbccdd7c3a79fa8bc30e7c93287",
          "sha1": "633f5b44ac7f9909dbaf20464427ccfabdedae4b",
          "md5": "c4cdaf7d0dc066ca8d3f7e1d161b9c42"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ait-1.2.13-feat-very-important-ait-update-dev+mc.1.20.1-sources.jar",
          "url": "ait-1.2.13-feat-very-important-ait-update-dev+mc.1.20.1-sources.jar",
          "size": 56967958,
          "sha512": "075b796bd7adf57468bdd09e76a9e3f3e72198d9674250d7768579ecf59550bffb018a8e781a1427cf32a159713a22aa3af04ba0f3d0eb9018947ef8ddef3919",
          "sha256": "1595dbf009426712aaa90da04f37728a190be1cbeb1cf05ef13e968ac4210886",
          "sha1": "c242d54898e8b64e0960de503907d2bd7c3fbea7",
          "md5": "b5b2b710db3e686ae893cbf92a845a7a"
        }
      ]
    }
  ]
}
