{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amble",
    "module": "ait",
    "version": "1.2.13-fix-ip-world-npe-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ait-1.2.13-fix-ip-world-npe-dev+mc.1.20.1.jar",
          "url": "ait-1.2.13-fix-ip-world-npe-dev+mc.1.20.1.jar",
          "size": 58599349,
          "sha512": "8beba4e3a2d28da8f710b232418398dd67d81fff33441ca24a4a7f1e3bf656e6e13b38e7b27cb196a8e9447017cab20f63ec2415a519660dcc6f849ed6cebea2",
          "sha256": "4efc35339600d9d42f01764b5f1565d44942bbed0c76e84aba5390467ea93310",
          "sha1": "9c6bae951b75e401192852b07ae447f3ce176dc8",
          "md5": "6d01fb6dc6c41eb37645176f35de57f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "dev.isxander",
          "module": "yet-another-config-lib",
          "version": {
            "requires": "3.6.1+1.20.1-fabric"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-1.2.13-fix-ip-world-npe-dev+mc.1.20.1.jar",
          "url": "ait-1.2.13-fix-ip-world-npe-dev+mc.1.20.1.jar",
          "size": 58599349,
          "sha512": "8beba4e3a2d28da8f710b232418398dd67d81fff33441ca24a4a7f1e3bf656e6e13b38e7b27cb196a8e9447017cab20f63ec2415a519660dcc6f849ed6cebea2",
          "sha256": "4efc35339600d9d42f01764b5f1565d44942bbed0c76e84aba5390467ea93310",
          "sha1": "9c6bae951b75e401192852b07ae447f3ce176dc8",
          "md5": "6d01fb6dc6c41eb37645176f35de57f2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ait-1.2.13-fix-ip-world-npe-dev+mc.1.20.1-sources.jar",
          "url": "ait-1.2.13-fix-ip-world-npe-dev+mc.1.20.1-sources.jar",
          "size": 57100609,
          "sha512": "66db1c753e13441a91e3bd2809e0d81cddc21a7dc91a202916bcfdf35c7793625b08624adff70fe6934a0aaa6fb070eae57af2bb7e0ee0d16dc5f340a84099fc",
          "sha256": "efd5cd7f7c06d364392ea9c872519079812d12cbaaf100a654149188d253664d",
          "sha1": "157568c678c263bb12b5e0d6cc01144bad546e79",
          "md5": "7c724decf4e10940bbca9cc0e72ab944"
        }
      ]
    }
  ]
}
