{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amble",
    "module": "stargate",
    "version": "0.0.0-build.269+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-build.138-feat-ports+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "stargate-0.0.0-build.269+mc.1.20.1.jar",
          "url": "stargate-0.0.0-build.269+mc.1.20.1.jar",
          "size": 7822984,
          "sha512": "8f364c7284888b52b404208513efed0f48cc6bb4b76217fcd33d1ad4cb41d6acf81721e9a3ae43fccbe055761d97f939ccfc218ecc5b0ea05a1ea42030a236d5",
          "sha256": "59df5a82b5da1beed90f86f0f040753d122579fbc9db357a2c497fdb3e694935",
          "sha1": "fe1181c55f3cc78784e755cc2540d1208adf7b0d",
          "md5": "79f36ba4765b9dc44ed909bf06d99aa0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-build.138-feat-ports+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "stargate-0.0.0-build.269+mc.1.20.1.jar",
          "url": "stargate-0.0.0-build.269+mc.1.20.1.jar",
          "size": 7822984,
          "sha512": "8f364c7284888b52b404208513efed0f48cc6bb4b76217fcd33d1ad4cb41d6acf81721e9a3ae43fccbe055761d97f939ccfc218ecc5b0ea05a1ea42030a236d5",
          "sha256": "59df5a82b5da1beed90f86f0f040753d122579fbc9db357a2c497fdb3e694935",
          "sha1": "fe1181c55f3cc78784e755cc2540d1208adf7b0d",
          "md5": "79f36ba4765b9dc44ed909bf06d99aa0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "stargate-0.0.0-build.269+mc.1.20.1-sources.jar",
          "url": "stargate-0.0.0-build.269+mc.1.20.1-sources.jar",
          "size": 7673871,
          "sha512": "e23f5028379dc09142d4cd73354ca16b6e8da1dbed0a06a5ec223a9f25c506ea164980a127156b0fcfae238d83deef9f4d0a8d30ce9ee33031edbb636d71f763",
          "sha256": "f7c2639715d89d1fb1857c956adae1d849bc97a2534007f7d5431fa0185c1487",
          "sha1": "ea611b1fc0a7b31819929585d1494881918df494",
          "md5": "30d9f23c79c04a110bf8ddcadb8aebf8"
        }
      ]
    }
  ]
}
