{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amble",
    "module": "lib",
    "version": "1.1.16-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.drtheo",
          "module": "multidim",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "scheduler",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "queue",
          "version": {
            "requires": "1.1.0-1.20"
          }
        }
      ],
      "files": [
        {
          "name": "lib-1.1.16-dev+mc.1.20.1.jar",
          "url": "lib-1.1.16-dev+mc.1.20.1.jar",
          "size": 665733,
          "sha512": "ac2fdf704b22446dde4a292f74a66d05f7b7bed89fa93757642f151317f1ff59b00a969937594b330ebf7c394c4a9d3dd02938bc7b8f27638633b0f15fefc7b2",
          "sha256": "05d9ec29149942824c80782bb02d4f1d4d47a23cc63a8a76bc96c7ec9d088b8e",
          "sha1": "42092569009c6ea4ceb95707445a5937cae400ea",
          "md5": "0b7d588589d3ba325fe1d391b24d5c28"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "multidim",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "scheduler",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "queue",
          "version": {
            "requires": "1.1.0-1.20"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-1.1.16-dev+mc.1.20.1.jar",
          "url": "lib-1.1.16-dev+mc.1.20.1.jar",
          "size": 665733,
          "sha512": "ac2fdf704b22446dde4a292f74a66d05f7b7bed89fa93757642f151317f1ff59b00a969937594b330ebf7c394c4a9d3dd02938bc7b8f27638633b0f15fefc7b2",
          "sha256": "05d9ec29149942824c80782bb02d4f1d4d47a23cc63a8a76bc96c7ec9d088b8e",
          "sha1": "42092569009c6ea4ceb95707445a5937cae400ea",
          "md5": "0b7d588589d3ba325fe1d391b24d5c28"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lib-1.1.16-dev+mc.1.20.1-sources.jar",
          "url": "lib-1.1.16-dev+mc.1.20.1-sources.jar",
          "size": 339288,
          "sha512": "09aa41cf1358b7e0c59a86a7d68f136c2647dc13bdeaa4677abc564e489af329fabdcf3448955623b71a9f58595ed5f12e9cc52bf2105d913accd3b8970e06ea",
          "sha256": "c98a88d562517c87e790b9133b59c566960a707484ab914b0502e4a3112b6e89",
          "sha1": "e54c787eab37188e33b548cc41f667ce0d761aa0",
          "md5": "33d14d08a64f91fa3d2edc59897729c3"
        }
      ]
    }
  ]
}
