{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amble",
    "module": "ait",
    "version": "1.2.13-feat-rift-ripping-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ait-1.2.13-feat-rift-ripping-dev+mc.1.20.1.jar",
          "url": "ait-1.2.13-feat-rift-ripping-dev+mc.1.20.1.jar",
          "size": 60685447,
          "sha512": "a5218df69d80ab519ef6106db7ffb3abb6756bfc401c76013b24364665be8e51532acd06ac3e61557ec62610c8bc34d78c8455dac957f0dbefd73825cace7d63",
          "sha256": "6de3aa87008ab7da9c91095fcf36fee494f7fbb3925073eef03bbc93fb11a17d",
          "sha1": "ad3d0b5d0dfdc6c0996df9c3251c12e8195237ee",
          "md5": "5a9ca9fb0b0ccdda2862104d17405f82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "dev.isxander",
          "module": "yet-another-config-lib",
          "version": {
            "requires": "3.6.1+1.20.1-fabric"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-1.2.13-feat-rift-ripping-dev+mc.1.20.1.jar",
          "url": "ait-1.2.13-feat-rift-ripping-dev+mc.1.20.1.jar",
          "size": 60685447,
          "sha512": "a5218df69d80ab519ef6106db7ffb3abb6756bfc401c76013b24364665be8e51532acd06ac3e61557ec62610c8bc34d78c8455dac957f0dbefd73825cace7d63",
          "sha256": "6de3aa87008ab7da9c91095fcf36fee494f7fbb3925073eef03bbc93fb11a17d",
          "sha1": "ad3d0b5d0dfdc6c0996df9c3251c12e8195237ee",
          "md5": "5a9ca9fb0b0ccdda2862104d17405f82"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ait-1.2.13-feat-rift-ripping-dev+mc.1.20.1-sources.jar",
          "url": "ait-1.2.13-feat-rift-ripping-dev+mc.1.20.1-sources.jar",
          "size": 59169075,
          "sha512": "e604bb3c92b3335afbd637164c46defbd1bd1dc205d4dfed4193e092404f6e1963b9ed938b03cd1d971a37bff7b086778689c2af4da4d6524accd442dbe0d2da",
          "sha256": "fa32fcbf16d3aa1391eb8181fce344b7a55fdec691fabfec2161f08f5fc4f167",
          "sha1": "e28e5620aeaf515cbc86b499a56a916072563d14",
          "md5": "2bf8f2af4da4ff993cc0ce9d2e9a6512"
        }
      ]
    }
  ]
}
