{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amblelabs",
    "module": "ait",
    "version": "1.3.0-fix-rift-render-ip-fallback-dev+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ait-1.3.0-fix-rift-render-ip-fallback-dev+mc.1.20.1.jar",
          "url": "ait-1.3.0-fix-rift-render-ip-fallback-dev+mc.1.20.1.jar",
          "size": 69784528,
          "sha512": "8735a1702cbd5b244e10b137a2895d291fc60c100cd04dfc1c02f18e87b3cffc6714ee2412f46b83bee201d33f94174ac199433915eedfcea2a79716e2b5ce00",
          "sha256": "a4f8278e162d9f9fada52e6114be6b0e93eee2d263c3acb814af4c9954e37b90",
          "sha1": "cdd2264d300cfdeac6819d757ab1e9f190211c05",
          "md5": "4b7d4f9b61eedd1107d05db65ac802ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.16-dev+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "dev.isxander",
          "module": "yet-another-config-lib",
          "version": {
            "requires": "3.6.1+1.20.1-fabric"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-1.3.0-fix-rift-render-ip-fallback-dev+mc.1.20.1.jar",
          "url": "ait-1.3.0-fix-rift-render-ip-fallback-dev+mc.1.20.1.jar",
          "size": 69784528,
          "sha512": "8735a1702cbd5b244e10b137a2895d291fc60c100cd04dfc1c02f18e87b3cffc6714ee2412f46b83bee201d33f94174ac199433915eedfcea2a79716e2b5ce00",
          "sha256": "a4f8278e162d9f9fada52e6114be6b0e93eee2d263c3acb814af4c9954e37b90",
          "sha1": "cdd2264d300cfdeac6819d757ab1e9f190211c05",
          "md5": "4b7d4f9b61eedd1107d05db65ac802ca"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ait-1.3.0-fix-rift-render-ip-fallback-dev+mc.1.20.1-sources.jar",
          "url": "ait-1.3.0-fix-rift-render-ip-fallback-dev+mc.1.20.1-sources.jar",
          "size": 68268247,
          "sha512": "62c4e3e63ab7796d717de965e573661c52a80b66fa97486505168b0e4154fb03c162548c7feadd302e59797bcd7214e5927429d9003e5a324816e5ef445af5e4",
          "sha256": "7d3bad09013b1fc8c658c4afa8cb7575dc03e4f00fabf559b527d4a8ebcf8432",
          "sha1": "f134e58a02c37d9ba7f358d2cb78d3558b76c6bc",
          "md5": "21b95c03b1253fe48d650f7f93f0ceb1"
        }
      ]
    }
  ]
}
