{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amble",
    "module": "ait",
    "version": "1.2.13-build.1911+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-build.139+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ait-1.2.13-build.1911+mc.1.20.1.jar",
          "url": "ait-1.2.13-build.1911+mc.1.20.1.jar",
          "size": 58423408,
          "sha512": "52cbca7d81fb9523e87defded88be3baf9d50bd2997a0aa8c487ba07e4d54294ce6427af502944f3f3710e58c9375a09068929550f92efeb57448e6d69ffbee3",
          "sha256": "c895e6de7d83a1652089fd37c121e3cfa1e8bb65dcf891ecc7b3ec414dec648b",
          "sha1": "1620b93a37a2d0ddedefbbb0cd9e632ad483aa6f",
          "md5": "de961b392e2eb040a7eac66d3dbe4ecc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "dev.amble",
          "module": "lib",
          "version": {
            "requires": "1.1.15-build.139+mc.1.20.1"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "dev.isxander",
          "module": "yet-another-config-lib",
          "version": {
            "requires": "3.6.1+1.20.1-fabric"
          }
        },
        {
          "group": "com.github.iPortalTeam.ImmersivePortalsMod",
          "module": "imm_ptl_core",
          "version": {
            "requires": "v3.3.9-mc1.20.1"
          }
        },
        {
          "group": "com.github.iPortalTeam.ImmersivePortalsMod",
          "module": "q_misc_util",
          "version": {
            "requires": "v3.3.9-mc1.20.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.20.0.112"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "jei",
          "version": {
            "requires": "15.20.0.112"
          }
        }
      ],
      "files": [
        {
          "name": "ait-1.2.13-build.1911+mc.1.20.1.jar",
          "url": "ait-1.2.13-build.1911+mc.1.20.1.jar",
          "size": 58423408,
          "sha512": "52cbca7d81fb9523e87defded88be3baf9d50bd2997a0aa8c487ba07e4d54294ce6427af502944f3f3710e58c9375a09068929550f92efeb57448e6d69ffbee3",
          "sha256": "c895e6de7d83a1652089fd37c121e3cfa1e8bb65dcf891ecc7b3ec414dec648b",
          "sha1": "1620b93a37a2d0ddedefbbb0cd9e632ad483aa6f",
          "md5": "de961b392e2eb040a7eac66d3dbe4ecc"
        }
      ]
    }
  ]
}
