{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amble",
    "module": "lib",
    "version": "1.1.15-build.138-feat-ports+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.drtheo",
          "module": "multidim",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "scheduler",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "queue",
          "version": {
            "requires": "1.1.0-1.20"
          }
        }
      ],
      "files": [
        {
          "name": "lib-1.1.15-build.138-feat-ports+mc.1.20.1.jar",
          "url": "lib-1.1.15-build.138-feat-ports+mc.1.20.1.jar",
          "size": 487661,
          "sha512": "02c539b1bc9cc3fb9a74d94af974d3d663d53401e09bf49ef40321a82c1da81b6918c8f7bc9c260447b3a0390ace0863d8bc81565063f126496357f6644c9f78",
          "sha256": "dd550f7604e5d4a2ea7f604c6490dfc1ec6e4377ba72af0d4914ee06fe103d19",
          "sha1": "781c3868c52043cbfc3d0aa2e7d35ab2c16b249d",
          "md5": "732a085f87789635893773f15edac950"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "multidim",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "scheduler",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "queue",
          "version": {
            "requires": "1.1.0-1.20"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib-1.1.15-build.138-feat-ports+mc.1.20.1.jar",
          "url": "lib-1.1.15-build.138-feat-ports+mc.1.20.1.jar",
          "size": 487661,
          "sha512": "02c539b1bc9cc3fb9a74d94af974d3d663d53401e09bf49ef40321a82c1da81b6918c8f7bc9c260447b3a0390ace0863d8bc81565063f126496357f6644c9f78",
          "sha256": "dd550f7604e5d4a2ea7f604c6490dfc1ec6e4377ba72af0d4914ee06fe103d19",
          "sha1": "781c3868c52043cbfc3d0aa2e7d35ab2c16b249d",
          "md5": "732a085f87789635893773f15edac950"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lib-1.1.15-build.138-feat-ports+mc.1.20.1-sources.jar",
          "url": "lib-1.1.15-build.138-feat-ports+mc.1.20.1-sources.jar",
          "size": 179753,
          "sha512": "4d89ca4eea1f7760a4f05c750bf4d84096d9fc9d3d7de4c718b5b6a5ce6a7dd5192c3e711d247bca61550b1c52cbe7f3b2c429e1c5db71d27287e7eb46de8f6a",
          "sha256": "d323ac16593ce6d5b06395a459769705f23ae1fed5cee4970f30918868a063c6",
          "sha1": "325dfb471f3c0e915c9c6dd55b8468a334e86671",
          "md5": "37d315510d19641b9a83ff4a42298279"
        }
      ]
    }
  ]
}
