{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.amble.lib",
    "module": "amble",
    "version": "1.1.15-build.135-feat-ports+mc.1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.drtheo",
          "module": "multidim",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "scheduler",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "queue",
          "version": {
            "requires": "1.1.0-1.20"
          }
        }
      ],
      "files": [
        {
          "name": "amble-1.1.15-build.135-feat-ports+mc.1.20.1.jar",
          "url": "amble-1.1.15-build.135-feat-ports+mc.1.20.1.jar",
          "size": 482431,
          "sha512": "35c73e915169a7c79c4fc1683afb862d3ff723f6834868f67ce704eb5340663e1a7bd9f5b579fef0060bb80ff5fc8d329b4b4d2a0d23f4314de67d87ae63dda4",
          "sha256": "5719f3bd6da82fae0f6da620c1d8db053aaebc4142fc2e139208708eb30d9906",
          "sha1": "d629229fea8e164712d484efa39c605622244fe4",
          "md5": "e356746573d24086c8bb3586afb111eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.objecthunter",
          "module": "exp4j",
          "version": {
            "requires": "0.4.8"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "multidim",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "scheduler",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "dev.drtheo",
          "module": "queue",
          "version": {
            "requires": "1.1.0-1.20"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "amble-1.1.15-build.135-feat-ports+mc.1.20.1.jar",
          "url": "amble-1.1.15-build.135-feat-ports+mc.1.20.1.jar",
          "size": 482431,
          "sha512": "35c73e915169a7c79c4fc1683afb862d3ff723f6834868f67ce704eb5340663e1a7bd9f5b579fef0060bb80ff5fc8d329b4b4d2a0d23f4314de67d87ae63dda4",
          "sha256": "5719f3bd6da82fae0f6da620c1d8db053aaebc4142fc2e139208708eb30d9906",
          "sha1": "d629229fea8e164712d484efa39c605622244fe4",
          "md5": "e356746573d24086c8bb3586afb111eb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "amble-1.1.15-build.135-feat-ports+mc.1.20.1-sources.jar",
          "url": "amble-1.1.15-build.135-feat-ports+mc.1.20.1-sources.jar",
          "size": 178078,
          "sha512": "70b7e305caeb47d0863d47670f8f37149929ea0b2188cf6b79fc701a9cc2b56788459cb7d12df971478ae921b2a8ccb58cccf1c753559ed2a9d783e903841e1d",
          "sha256": "c9d8d6efdf24d25a20ab23892fbab8824c0b55b273b766fa1215df158adef82d",
          "sha1": "29d76b789e4a0be7686016915eb9597bd6ff68f7",
          "md5": "9fa5616b0234d190aada381068c7691a"
        }
      ]
    }
  ]
}
